[package]
name = "cms-cots-fsw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
gpiod = "0.3.0"
prost = "0.13.5"
spidev = "0.6.0"
tokio = { version = "1.34", features = ["full"] }
tonic = "*"

[build-dependencies]
tonic-build = "*"
