[project]
name = "cms-cots-fsw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "openpyxl>=3.1.5",
    "polars>=1.24.0",
    "pyqt5>=5.15.11",
    "synnax>=0.39.0",
]
