#!/usr/bin/env python3

import subprocess

subprocess.run(["scp", "-P", "22", 
                "bin/fsw", 
                "tools/end", 
                "tools/run", 
                "root@sedsdaq.ecn.purdue.edu:/var/lib"])
