#!/usr/bin/env python3

import subprocess

subprocess.run(["scp", "-P", "22", 
                "build/fsw", 
                "tools/end", 
                "tools/run", 
                "root@192.168.2.110:/var/lib"])
